import React from "react"
import type { Metadata } from "next"
import Link from "next/link"
import { Inter } from "next/font/google"
import ReactQueryClientProvider from "@/app/lib/reactQueryClientProvider"
import { navigationMenuTriggerStyle } from "@/components/ui/navigation-menu"
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
} from "@/components/ui/navigation-menu"
import { Toaster as Sonner } from "@/components/ui/sonner"
import { Toaster } from "@/components/ui/toaster"
import Logo from "@/components/ui/Logo"
import { Button } from "@/components/ui/button"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClientProvider>
          <div className="container flex h-14 max-w-screen-2xl items-center justify-between">
            <NavigationMenu>
              <NavigationMenuList>
                {/* Left */}
                {/* Logo */}
                <NavigationMenuItem>
                  <Link href="/">
                    <Logo className="mx-2" />
                  </Link>
                </NavigationMenuItem>

                <NavigationMenuItem>
                  <Link href="/recommendation" legacyBehavior passHref>
                    <NavigationMenuLink className={navigationMenuTriggerStyle()}>
                    Recommendation
                    </NavigationMenuLink>
                  </Link>
                </NavigationMenuItem>

                <NavigationMenuItem>
                  <Link href="/book" legacyBehavior passHref>
                    <NavigationMenuLink className={navigationMenuTriggerStyle()}>
                    Book
                    </NavigationMenuLink>
                  </Link>
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu>

            {/* Right */}
            <Link href="/admin" legacyBehavior passHref>
              <Button>
              Admin
              </Button>
            </Link>
          </div>
          <Sonner />
          <Toaster />
          {children}
        </ReactQueryClientProvider>
      </body>
    </html>
  )
}
